--------------------------------------------------------------------------------
-- Module      : clk_div_v2
-- Description : Clock divider -- version 2 (optimised).
--
-- Key change vs v1:
--   clock_pmod is now exactly 20 MHz (ADC SPI clock maximum per datasheet),
--   generated by a DDR divide-by-5 circuit using BOTH rising and falling
--   edges of the 100 MHz system clock.
--
-- DDR divide-by-5 principle:
--   A mod-5 counter advances on rising edges of clk (100 MHz).
--   pmod_r is combinatorially HIGH when counter = 0 or 1 (20 ns window).
--   pmod_f samples pmod_r on each falling edge of clk (5 ns delay).
--   clock_pmod = pmod_r OR pmod_f -> 50% duty cycle at 20 MHz.
--
--   Timing diagram (one 50 ns period):
--   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--   + t(ns):  0    5   10   15   20   25   30   35   40   45  50+
--   + clk:    R    F    R    F    R    F    R    F    R    F    R+
--   + cnt:    0         1         2         3         4         0+
--   + pmod_r: 1         1         0         0         0         1+
--   + pmod_f:      1         1         0         0         0    +
--   + OR:     1    1    1    1    0    0    0    0    0    0    1+
--   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--   HIGH = 25 ns, LOW = 25 ns -> 20 MHz, 50% duty cycle ?
--
--   clock_conv : 20 MHz -- set to maximum in v2, same DDR signal as clock_pmod.
--                The FSM uses it as a gate: starts a new conversion when
--                clock_conv='1' AND adc_busy='0'. At 20 MHz this gives the
--                highest possible sample rate within the ADC quiet-time spec
--                (t_quiet,min = 50 ns -> f_max = 20 MHz per datasheet).
--
-- Synthesis note:
--   The falling-edge flip-flop (pmod_f) is synthesised as a standard FF
--   with inverted clock. Xilinx ISE/Vivado both support this natively on
--   Artix-7. The OR gate is a single LUT1.
--------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity clk_div_v2 is
    port (
        reset      : in  std_logic;
        clock      : in  std_logic;   -- 100 MHz system clock
        clock_pmod : out std_logic;   -- exactly 20 MHz, 50% duty (DDR /5)
        clock_conv : out std_logic    -- exactly 20 MHz, same DDR signal (max rate)
    );
end clk_div_v2;

architecture behavioral of clk_div_v2 is

    -- DDR divide-by-5 signals
    signal cnt    : integer range 0 to 4 := 0;
    signal pmod_r : std_logic := '0';   -- rising-edge domain
    signal pmod_f : std_logic := '0';   -- falling-edge domain (half-cycle delay)
    signal ddr_out : std_logic := '0';

begin

    -- ++ Mod-5 counter on rising edge ++++++++++++++++++++++++++++++++++++++++
    process(clock, reset)
    begin
        if reset = '1' then
            cnt <= 0;
        elsif rising_edge(clock) then
            if cnt = 4 then
                cnt <= 0;
            else
                cnt <= cnt + 1;
            end if;
        end if;
    end process;

    -- ++ pmod_r: HIGH for counts 0 and 1 (combinatorial) ++++++++++++++++++++
    pmod_r <= '1' when (cnt = 0 or cnt = 1) else '0';

    -- ++ pmod_f: pmod_r delayed by half a clock cycle (falling-edge FF) +++++
    process(clock, reset)
    begin
        if reset = '1' then
            pmod_f <= '0';
        elsif falling_edge(clock) then
            pmod_f <= pmod_r;
        end if;
    end process;

    -- ++ DDR output: both clock_pmod and clock_conv run at 20 MHz ++++++++++++
    ddr_out    <= pmod_r or pmod_f;
    clock_pmod <= ddr_out;
    clock_conv <= ddr_out;   -- same 20 MHz signal: maximum conversion rate

end behavioral;
